# Generated by Django 3.0.8 on 2020-08-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200818_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingDescription',
            field=models.TextField(default='Enter description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Enter comment'),
        ),
    ]
