# Generated by Django 3.0.8 on 2020-08-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200818_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(null=True),
        ),
    ]
