# Generated by Django 3.0.8 on 2020-08-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200819_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='listingPrice',
        ),
    ]
