# Generated by Django 3.0.8 on 2020-08-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200823_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='biddedItemName',
        ),
        migrations.AddField(
            model_name='bid',
            name='currentBidPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='startingBid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemThisBidIsOn', to='auctions.Bid'),
        ),
    ]
