# Generated by Django 3.0.8 on 2020-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200823_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='startingBid',
        ),
        migrations.AddField(
            model_name='listing',
            name='currentBid',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='bid',
        ),
    ]
