# Generated by Django 3.0.8 on 2020-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200823_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listingPrice',
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.IntegerField(),
        ),
    ]
