# Generated by Django 3.0.8 on 2020-08-23 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200823_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currentHighestBidOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highestBidderOn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
